version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
      - "5555:5555"
    volumes:
      - ./backend/uploads:/app/uploads
      - /app/node_modules  # prevent host node_modules from overwriting container's
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bahmini?schema=public
      - PORT=5555
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bahmni-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bahmini
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bahmini"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bahmni-network

volumes:
  postgres_data:

networks:
  bahmni-network:
    driver: bridge