version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/backend/uploads
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/bahmini
      - PORT=5000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bahmni-network

  mongodb:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bahmini
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bahmni-network

volumes:
  mongo_data:

networks:
  bahmni-network:
    driver: bridge
